// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Ix9ngBdgar9-fP_LN3Oyo5leKDjjPfM',
    appId: '1:367661405186:web:12c7edd5a88c08e780031b',
    messagingSenderId: '367661405186',
    projectId: 'chatapp-f775b',
    authDomain: 'chatapp-f775b.firebaseapp.com',
    storageBucket: 'chatapp-f775b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3jMid9oEgY-m5Nr1oWdKXmQeUI-KU5M4',
    appId: '1:367661405186:android:586dfdfe2fbf992380031b',
    messagingSenderId: '367661405186',
    projectId: 'chatapp-f775b',
    storageBucket: 'chatapp-f775b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJlxaCZmdwcOASbUFOXLqrh_16eRXlLiE',
    appId: '1:367661405186:ios:90233d421c80539e80031b',
    messagingSenderId: '367661405186',
    projectId: 'chatapp-f775b',
    storageBucket: 'chatapp-f775b.appspot.com',
    iosBundleId: 'com.example.chatRoomLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJlxaCZmdwcOASbUFOXLqrh_16eRXlLiE',
    appId: '1:367661405186:ios:83bc64311a0e1d3280031b',
    messagingSenderId: '367661405186',
    projectId: 'chatapp-f775b',
    storageBucket: 'chatapp-f775b.appspot.com',
    iosBundleId: 'com.example.chatRoomLearning.RunnerTests',
  );
}
